name: abalone-ml
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - python=3.11
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - seaborn
  - xgboost
  - shap
  - ipywidgets
  - lime
  - ipython
  - ipykernel
  - notebook
prefix: C:\Anaconda3\envs\abalone-ml
